#!/usr/bin/env bash
set -euo pipefail

: "${CUR_SCRIPT:=$(basename "${BASH_SOURCE[0]}")}"
export CUR_SCRIPT
: "${PORTMASON_SHARE:="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"}"
. "${PORTMASON_SHARE}/pm-helpers" "$@"

main() {
    # run the adapter provisioning script, if it exists
    local file="${PORTMASON_SHARE}/pm-provision-${ADAPTER_CODE}"
    [[ -r "$file" ]] && . "$file" "$@"
}

main "$@"
