#!/usr/bin/env bash
set -euo pipefail

script_name="$(basename "${BASH_SOURCE[0]}")"

# shellcheck source=/dev/null
source "${PORTMASON_SHARE}/pm-helpers" "$@"

boilerplate_configure() {
    # For WordPress, ensure core is installed and theme is active.
    # WP_* variables come from the env file.
    install_core

    ensure_theme "$@"
    # rc=$?
    # if (( rc!=0)); then
    #     # we installed or activated a theme, so let's remove default content
    #     remove_content
    # fi

    # wp option update etal_setup_state 'custom_config_applied'
    # echo "✅ WordPress Theme ''site options successfully configured."
}

boilerplate_configure
