#!/usr/bin/env bash
set -euo pipefail

script_name="$(basename "${BASH_SOURCE[0]}")"
. "${PORTMASON_SHARE}/pm-helpers"

main() {
    echo "[${script_name}] Start setting up wp ..."
    install_core "$@"
    local rc=$?

    case $rc in
        1)
            echo "[${script_name}] ======================="
            echo "[${script_name}] ======================="
            echo "[${script_name}] =====Core installed====="
            echo "[${script_name}] ======================="
            echo "[${script_name}] ======================="
            ;;
        *) ;;
    esac
    echo "[${script_name}] End setting up wp"
}

main "$@"



