#!/usr/bin/env bash
set -euo pipefail

export DEPLOY_ENV="${DEPLOY_ENV:-${DEPLOY_ENV:-}}"

#. "/usr/local/bin/sys-cd-project-root"

: "${CUR_SCRIPT:=$(basename "${BASH_SOURCE[0]:-${0:-}}")}"
export CUR_SCRIPT

main() {
    export PROJECT_SERVICES=

    : "${PORTMASON_SHARE:="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-${0:-}}")" && pwd -P)"}"

    . "${PORTMASON_SHARE}/pm-helpers" "$@"

    if [[ -n "${DEPLOY_ENV:-}" && "${DEPLOY_ENV}" != "dev" && "${DEPLOY_ENV}" != "sys" ]]; then
        . "${PORTMASON_SHARE}/pm-sync-deploy-from-root" --overwrite
    fi

    "${PORTMASON_SHARE}/pm-generate-config"

    stage_portmason "archive" "cagent" "*cosign*" "*log" # Exclude archive/, cagent, cosign files, log files

    # run the adapter provisioning script, if it exists
    local file="${PORTMASON_SHARE}/pm-provision-${ADAPTER_CODE}"
    [[ -r "$file" ]] && . "$file" "$@"

    # run the optional adapter setup script
    file="${PORTMASON_SHARE}/pm-setup-${ADAPTER_CODE}"
    [[ -r "$file" ]] && . "$file" "$@"

    # run the optional runtime setup script
    file="${PORTMASON_SHARE}/pm-setup-${RUNTIME_CODE}"
    [[ -r "$file" ]] && . "$file" "$@"

    # if a custom setup file exists, it must handle all deployment tasks for the project,
    # Otherwise, run the standard runtime deploy followed by the standard adapter deploy
    file="${SCRIPT_DIR}/setup"
    if [[ -r "$file" ]]; then
        . "$file" "$@"
        local rc=$?

        case "$rc" in
            0)
                log "Success."
                ;;
            1)
                die "General error:" $rc
                ;;
            2)
                die "Misuse of shell builtins or command-specific code." $rc
                ;;
            *)
                fatal_error "Unexpected error code:"  $rc
                ;;
        esac
    else
        # run the optional runtime deploy script
            file="${PORTMASON_SHARE}/pm-deploy-${RUNTIME_CODE}"
            [[ -r "$file" ]] && . "$file" "$@"

        # run the optional adapter deploy script
        if declare -F pm_bridge_deploy >/dev/null 2>&1; then
            log INFO "pm-setup: using bridge deploy hook: pm_bridge_deploy"
            pm_bridge_deploy "$@"
        else
            file="${PORTMASON_SHARE}/pm-deploy-${ADAPTER_CODE}"
            [[ -r "$file" ]] && . "$file" "$@"
        fi
    fi
}

main "$@"
